"""
Django settings for afrilux_sav project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
import importlib.util
import os
from pathlib import Path
import sys
from urllib.parse import urlparse

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env(env_path: Path):
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not key or key in os.environ:
            continue
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
            value = value[1:-1]
        os.environ[key] = value


def _env_bool(name: str, default: bool = False) -> bool:
    raw_value = os.getenv(name)
    if raw_value is None:
        return default
    return raw_value.strip().lower() in {"1", "true", "yes", "on", "oui"}


def _env_list(name: str, default: str = "") -> list[str]:
    return [
        item.strip()
        for item in os.getenv(name, default).split(",")
        if item.strip()
    ]


def _hostname_from_url(value: str) -> str:
    try:
        return (urlparse(value).hostname or "").strip()
    except ValueError:
        return ""


def _argon2_hasher_available() -> bool:
    if importlib.util.find_spec("argon2") is None:
        return False
    try:
        importlib.import_module("argon2.low_level")
    except Exception:  # noqa: BLE001
        return False
    return True


_load_local_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = _env_bool("DJANGO_DEBUG", False)

DEV_SECRET_KEY = "django-insecure-local-dev-only-change-me"
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "").strip() or DEV_SECRET_KEY
USING_DEV_SECRET_KEY = SECRET_KEY == DEV_SECRET_KEY
if USING_DEV_SECRET_KEY and not DEBUG and "test" not in sys.argv:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY doit etre defini dans l'environnement ou dans afrilux_sav/.env quand DJANGO_DEBUG=false."
    )

# SECURITY WARNING: don't run with debug turned on in production!

RENDER_EXTERNAL_HOSTNAME = os.getenv("RENDER_EXTERNAL_HOSTNAME", "").strip()
RENDER_EXTERNAL_URL = os.getenv("RENDER_EXTERNAL_URL", "").strip()
SAV_PUBLIC_BASE_URL = os.getenv("SAV_PUBLIC_BASE_URL", "").strip() or RENDER_EXTERNAL_URL or "http://127.0.0.1:8000"

ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost,10.0.2.2,testserver")
for derived_host in {RENDER_EXTERNAL_HOSTNAME, _hostname_from_url(SAV_PUBLIC_BASE_URL)}:
    if derived_host and derived_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(derived_host)
SERVE_STATIC_LOCAL = _env_bool("DJANGO_SERVE_STATIC_LOCAL", bool(os.getenv("RENDER")))
USE_WHITENOISE_STATIC_STORAGE = (
    SERVE_STATIC_LOCAL
    and not DEBUG
    and "runserver" not in sys.argv
    and "test" not in sys.argv
)
USE_MANIFEST_STATIC_STORAGE = (
    USE_WHITENOISE_STATIC_STORAGE
    and _env_bool("DJANGO_USE_MANIFEST_STATIC_STORAGE", False)
)
WHITENOISE_MANIFEST_STRICT = _env_bool("WHITENOISE_MANIFEST_STRICT", False)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'sav',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "sav.middleware.CurrentRequestMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
if SERVE_STATIC_LOCAL:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = "afrilux_sav.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.i18n",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "sav.context_processors.sav_shell",
            ],
        },
    },
]

WSGI_APPLICATION = "afrilux_sav.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_ENGINE = os.getenv("DJANGO_DB_ENGINE", "").strip()
if not DATABASE_ENGINE and os.getenv("DJANGO_DB_HOST", "").strip():
    DATABASE_ENGINE = "django.db.backends.postgresql"
DATABASE_ENGINE = DATABASE_ENGINE or "django.db.backends.sqlite3"

DATABASE_NAME_DEFAULT = "afrilux_sav"
if DATABASE_ENGINE == "django.db.backends.sqlite3":
    DATABASE_NAME_DEFAULT = str(BASE_DIR / "db.sqlite3")

DATABASES = {
    "default": {
        "ENGINE": DATABASE_ENGINE,
        "NAME": os.getenv("DJANGO_DB_NAME", DATABASE_NAME_DEFAULT),
        "USER": os.getenv("DJANGO_DB_USER", ""),
        "PASSWORD": os.getenv("DJANGO_DB_PASSWORD", ""),
        "HOST": os.getenv("DJANGO_DB_HOST", ""),
        "PORT": os.getenv("DJANGO_DB_PORT", ""),
        "CONN_MAX_AGE": int(os.getenv("DJANGO_DB_CONN_MAX_AGE", "60")),
    }
}
if "postgresql" in DATABASE_ENGINE:
    DATABASES["default"]["OPTIONS"] = {}
    sslmode = os.getenv("DJANGO_DB_SSLMODE", "prefer").strip()
    if sslmode:
        DATABASES["default"]["OPTIONS"]["sslmode"] = sslmode


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
]
if _argon2_hasher_available():
    PASSWORD_HASHERS.insert(0, "django.contrib.auth.hashers.Argon2PasswordHasher")


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "fr"
LANGUAGES = [
    ("fr", "Francais"),
    ("en", "English"),
]
LANGUAGE_COOKIE_NAME = "django_language"
LANGUAGE_COOKIE_PATH = "/"

TIME_ZONE = "Africa/Douala"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = Path(os.getenv("DJANGO_MEDIA_ROOT", str(BASE_DIR / "media")))
STATIC_ROOT = Path(os.getenv("DJANGO_STATIC_ROOT", str(BASE_DIR / "staticfiles")))
BACKUP_ROOT = Path(os.getenv("SAV_BACKUP_DIR", str(BASE_DIR / "backups")))
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if USE_MANIFEST_STATIC_STORAGE
            else (
                "whitenoise.storage.CompressedStaticFilesStorage"
                if USE_WHITENOISE_STATIC_STORAGE
                else "django.contrib.staticfiles.storage.StaticFilesStorage"
            )
        ),
    },
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "sav.User"

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-5.1")
OPENAI_BASE_URL = os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1")
OPENAI_REASONING_EFFORT = os.getenv("OPENAI_REASONING_EFFORT", "")

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() == "true"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "no-reply@afrilux.local")
INBOUND_EMAIL_IMAP_HOST = os.getenv("INBOUND_EMAIL_IMAP_HOST", "")
INBOUND_EMAIL_IMAP_PORT = int(os.getenv("INBOUND_EMAIL_IMAP_PORT", "993"))
INBOUND_EMAIL_IMAP_USER = os.getenv("INBOUND_EMAIL_IMAP_USER", "")
INBOUND_EMAIL_IMAP_PASSWORD = os.getenv("INBOUND_EMAIL_IMAP_PASSWORD", "")
INBOUND_EMAIL_IMAP_USE_SSL = os.getenv("INBOUND_EMAIL_IMAP_USE_SSL", "true").lower() == "true"
INBOUND_EMAIL_IMAP_MAILBOX = os.getenv("INBOUND_EMAIL_IMAP_MAILBOX", "INBOX")
INBOUND_EMAIL_IMAP_SEARCH = os.getenv("INBOUND_EMAIL_IMAP_SEARCH", "UNSEEN")

TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN", "")
TWILIO_SMS_FROM = os.getenv("TWILIO_SMS_FROM", "")
TWILIO_WHATSAPP_FROM = os.getenv("TWILIO_WHATSAPP_FROM", "")
TWILIO_STATUS_CALLBACK_URL = os.getenv("TWILIO_STATUS_CALLBACK_URL", "")

FIREBASE_PROJECT_ID = os.getenv("FIREBASE_PROJECT_ID", "")
FIREBASE_CREDENTIALS_FILE = os.getenv("FIREBASE_CREDENTIALS_FILE", "")

REDIS_URL = os.getenv("REDIS_URL", "").strip()
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "TIMEOUT": int(os.getenv("DJANGO_CACHE_TIMEOUT", "300")),
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "afrilux-sav-local",
            "TIMEOUT": int(os.getenv("DJANGO_CACHE_TIMEOUT", "300")),
        }
    }

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PAGINATION_CLASS": "sav.pagination.OptionalPageNumberPagination",
    "PAGE_SIZE": int(os.getenv("API_DEFAULT_PAGE_SIZE", "25")),
    "URL_FORMAT_OVERRIDE": None,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(os.getenv("JWT_ACCESS_MINUTES", "30"))),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.getenv("JWT_REFRESH_DAYS", "7"))),
}

AUTHENTICATION_BACKENDS = [
    "sav.auth_backends.EmailOrUsernameBackend",
]

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/workspace/"
LOGOUT_REDIRECT_URL = "/login/"

SESSION_COOKIE_AGE = int(os.getenv("SESSION_COOKIE_AGE", str(60 * 60 * 8)))
SESSION_EXPIRE_AT_BROWSER_CLOSE = _env_bool("SESSION_EXPIRE_AT_BROWSER_CLOSE", False)
SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", False)
SESSION_COOKIE_HTTPONLY = _env_bool("SESSION_COOKIE_HTTPONLY", True)
SESSION_COOKIE_SAMESITE = os.getenv("SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", False)
CSRF_COOKIE_HTTPONLY = _env_bool("CSRF_COOKIE_HTTPONLY", False)
CSRF_COOKIE_SAMESITE = os.getenv("CSRF_COOKIE_SAMESITE", "Lax")
CSRF_TRUSTED_ORIGINS = _env_list("CSRF_TRUSTED_ORIGINS")
if SAV_PUBLIC_BASE_URL.startswith("https://") and SAV_PUBLIC_BASE_URL not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(SAV_PUBLIC_BASE_URL)
SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", False)
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = _env_bool("SECURE_HSTS_PRELOAD", False)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"
