from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .forms import SavAuthenticationForm
from .web_views import (
    AdministrationPageView,
    AnalyticsPageView,
    ClientRegisterView,
    DashboardPageView,
    HomeRedirectView,
    KnowledgeArticleDetailView,
    KnowledgeArticleListView,
    NotificationListView,
    NotificationMarkReadView,
    PredictiveAlertListView,
    ProductCreateView,
    ProductDeleteView,
    ProductDetailView,
    ProductListView,
    ProductPredictiveAnalysisView,
    ProductUpdateView,
    ReportingPageView,
    SupportPageView,
    TechnicianSpaceView,
    TicketAgenticResolutionView,
    TicketAttachmentCreateView,
    TicketAutomationRunView,
    TicketConfirmResolutionView,
    TicketCreditAccountView,
    TicketCreateView,
    TicketDetailView,
    TicketInterventionCreateView,
    TicketInterventionPdfView,
    TicketListView,
    TicketMessageCreateView,
    TicketReopenView,
    TicketUpdateView,
    TechnicianPlanningPageView,
)

urlpatterns = [
    path("", HomeRedirectView.as_view(), name="home"),
    path(
        "login/",
        LoginView.as_view(
            template_name="sav/login.html",
            authentication_form=SavAuthenticationForm,
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path("register/", ClientRegisterView.as_view(), name="register"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("dashboard/", DashboardPageView.as_view(), name="dashboard"),
    path("technician-space/", TechnicianSpaceView.as_view(), name="technician-space"),
    path("planning/", TechnicianPlanningPageView.as_view(), name="planning-page"),
    path("administration/", AdministrationPageView.as_view(), name="administration-page"),
    path("reporting/", ReportingPageView.as_view(), name="reporting-page"),
    path("support/", SupportPageView.as_view(), name="support-page"),
    path("tickets/", TicketListView.as_view(), name="ticket-list"),
    path("tickets/new/", TicketCreateView.as_view(), name="ticket-create"),
    path("tickets/<int:pk>/", TicketDetailView.as_view(), name="ticket-detail"),
    path("tickets/<int:pk>/edit/", TicketUpdateView.as_view(), name="ticket-update"),
    path("tickets/<int:pk>/message/", TicketMessageCreateView.as_view(), name="ticket-message-create"),
    path("tickets/<int:pk>/attachments/", TicketAttachmentCreateView.as_view(), name="ticket-attachment-create"),
    path("tickets/<int:pk>/confirm-resolution/", TicketConfirmResolutionView.as_view(), name="ticket-confirm-resolution"),
    path("tickets/<int:pk>/reopen/", TicketReopenView.as_view(), name="ticket-reopen-web"),
    path("tickets/<int:pk>/interventions/", TicketInterventionCreateView.as_view(), name="ticket-intervention-create"),
    path(
        "tickets/<int:ticket_pk>/interventions/<int:intervention_pk>/pdf/",
        TicketInterventionPdfView.as_view(),
        name="ticket-intervention-pdf",
    ),
    path("tickets/<int:pk>/agentic-resolution/", TicketAgenticResolutionView.as_view(), name="ticket-agentic-web"),
    path("tickets/<int:pk>/run-automation/", TicketAutomationRunView.as_view(), name="ticket-automation-web"),
    path("tickets/<int:pk>/credit-account/", TicketCreditAccountView.as_view(), name="ticket-credit-account"),
    path("products/", ProductListView.as_view(), name="product-list"),
    path("products/new/", ProductCreateView.as_view(), name="product-create"),
    path("products/<int:pk>/edit/", ProductUpdateView.as_view(), name="product-update"),
    path("products/<int:pk>/delete/", ProductDeleteView.as_view(), name="product-delete"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="product-detail"),
    path("products/<int:pk>/predictive-analysis/", ProductPredictiveAnalysisView.as_view(), name="product-predictive-web"),
    path("alerts/", PredictiveAlertListView.as_view(), name="alert-list"),
    path("knowledge/", KnowledgeArticleListView.as_view(), name="knowledge-list"),
    path("knowledge/<slug:slug>/", KnowledgeArticleDetailView.as_view(), name="knowledge-detail"),
    path("notifications/", NotificationListView.as_view(), name="notifications"),
    path("notifications/<int:pk>/read/", NotificationMarkReadView.as_view(), name="notification-read"),
    path("analytics/", AnalyticsPageView.as_view(), name="analytics-page"),
]
