from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .forms import SavAuthenticationForm
from .web_views import (
    AdministrationPageView,
    AnalyticsPageView,
    ClientRegisterView,
    DashboardPageView,
    HomeRedirectView,
    KnowledgeArticleDetailView,
    KnowledgeArticleListView,
    MaintenanceProgramCreateView,
    MaintenanceProgramListView,
    MaintenanceProgramPublishView,
    MaintenanceReportValidateView,
    MaintenanceTicketAcknowledgeView,
    MaintenanceTicketCancelView,
    MaintenanceTicketCloseView,
    MaintenanceTicketStartView,
    NotificationListView,
    NotificationMarkReadView,
    PredictiveAlertListView,
    ProductCreateView,
    ProductDeleteView,
    ProductDetailView,
    ProductListView,
    ProductPredictiveAnalysisView,
    ProductUpdateView,
    RoleWorkspaceRedirectView,
    ReportingPageView,
    RealtimeEventsView,
    SupportPageView,
    ServiceWorkerView,
    TechnicianSpaceView,
    TicketAgenticResolutionView,
    TicketAssignTeamView,
    TicketAssignTechnicianView,
    TicketAttachmentCreateView,
    TicketAutomationRunView,
    TicketCloseDossierView,
    TicketConfirmResolutionView,
    TicketCreditAccountView,
    TicketCreateView,
    TicketDetailView,
    TicketEscalationContinueView,
    TicketEscalationDeclineView,
    TicketEscalationSolutionView,
    TicketEscalateView,
    TicketFeedbackCreateView,
    TicketInterventionCreateView,
    TicketInterventionPdfView,
    TicketListView,
    TicketMessageCreateView,
    TicketPlanningConfirmView,
    TicketPlanningProposeView,
    TicketReopenView,
    TicketRequestFinishView,
    TicketRequestStartView,
    TicketUpdateView,
    TicketValidateFinishView,
    TicketValidateStartView,
    TicketWaitPartView,
    TechnicianPlanningPageView,
    WebManifestView,
)

urlpatterns = [
    path("", HomeRedirectView.as_view(), name="home"),
    path("manifest.webmanifest", WebManifestView.as_view(), name="web-manifest"),
    path("service-worker.js", ServiceWorkerView.as_view(), name="service-worker"),
    path(
        "login/",
        LoginView.as_view(
            template_name="sav/login.html",
            authentication_form=SavAuthenticationForm,
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path("register/", ClientRegisterView.as_view(), name="register"),
    path("logout/", LogoutView.as_view(next_page="login"), name="logout"),
    path("workspace/", RoleWorkspaceRedirectView.as_view(), name="workspace"),
    path("events/", RealtimeEventsView.as_view(), name="realtime-events"),
    path("dashboard/", DashboardPageView.as_view(), name="dashboard"),
    path("technician-space/", TechnicianSpaceView.as_view(), name="technician-space"),
    path("planning/", TechnicianPlanningPageView.as_view(), name="planning-page"),
    path("maintenance/", MaintenanceProgramListView.as_view(), name="maintenance-program"),
    path("maintenance/new/", MaintenanceProgramCreateView.as_view(), name="maintenance-program-create"),
    path("maintenance/<int:pk>/publish/", MaintenanceProgramPublishView.as_view(), name="maintenance-program-publish"),
    path("maintenance/tickets/<int:pk>/acknowledge/", MaintenanceTicketAcknowledgeView.as_view(), name="maintenance-ticket-acknowledge"),
    path("maintenance/tickets/<int:pk>/cancel/", MaintenanceTicketCancelView.as_view(), name="maintenance-ticket-cancel"),
    path("maintenance/tickets/<int:pk>/start/", MaintenanceTicketStartView.as_view(), name="maintenance-ticket-start"),
    path("maintenance/tickets/<int:pk>/close/", MaintenanceTicketCloseView.as_view(), name="maintenance-ticket-close"),
    path("maintenance/tickets/<int:pk>/validate-report/", MaintenanceReportValidateView.as_view(), name="maintenance-report-validate"),
    path("administration/", AdministrationPageView.as_view(), name="administration-page"),
    path("reporting/", ReportingPageView.as_view(), name="reporting-page"),
    path("support/", SupportPageView.as_view(), name="support-page"),
    path("tickets/", TicketListView.as_view(), name="ticket-list"),
    path("tickets/new/", TicketCreateView.as_view(), name="ticket-create"),
    path("tickets/<int:pk>/", TicketDetailView.as_view(), name="ticket-detail"),
    path("tickets/<int:pk>/edit/", TicketUpdateView.as_view(), name="ticket-update"),
    path("tickets/<int:pk>/message/", TicketMessageCreateView.as_view(), name="ticket-message-create"),
    path("tickets/<int:pk>/attachments/", TicketAttachmentCreateView.as_view(), name="ticket-attachment-create"),
    path("tickets/<int:pk>/confirm-resolution/", TicketConfirmResolutionView.as_view(), name="ticket-confirm-resolution"),
    path("tickets/<int:pk>/feedback/", TicketFeedbackCreateView.as_view(), name="ticket-feedback-create-web"),
    path("tickets/<int:pk>/reopen/", TicketReopenView.as_view(), name="ticket-reopen-web"),
    path("tickets/<int:pk>/escalate/", TicketEscalateView.as_view(), name="ticket-escalate-web"),
    path("tickets/<int:pk>/escalation/solution/", TicketEscalationSolutionView.as_view(), name="ticket-escalation-solution-web"),
    path("tickets/<int:pk>/escalation/decline/", TicketEscalationDeclineView.as_view(), name="ticket-escalation-decline-web"),
    path("tickets/<int:pk>/escalation/continue/", TicketEscalationContinueView.as_view(), name="ticket-escalation-continue-web"),
    path("tickets/<int:pk>/assign-technician/", TicketAssignTechnicianView.as_view(), name="ticket-assign-technician-web"),
    path("tickets/<int:pk>/assign-team/", TicketAssignTeamView.as_view(), name="ticket-assign-team-web"),
    path("tickets/<int:pk>/plan/", TicketPlanningProposeView.as_view(), name="ticket-plan-web"),
    path("tickets/<int:pk>/confirm-planning/", TicketPlanningConfirmView.as_view(), name="ticket-confirm-planning-web"),
    path("tickets/<int:pk>/request-start/", TicketRequestStartView.as_view(), name="ticket-request-start-web"),
    path("tickets/<int:pk>/validate-start/", TicketValidateStartView.as_view(), name="ticket-validate-start-web"),
    path("tickets/<int:pk>/request-finish/", TicketRequestFinishView.as_view(), name="ticket-request-finish-web"),
    path("tickets/<int:pk>/validate-finish/", TicketValidateFinishView.as_view(), name="ticket-validate-finish-web"),
    path("tickets/<int:pk>/wait-part/", TicketWaitPartView.as_view(), name="ticket-wait-part-web"),
    path("tickets/<int:pk>/close-dossier/", TicketCloseDossierView.as_view(), name="ticket-close-dossier-web"),
    path("tickets/<int:pk>/interventions/", TicketInterventionCreateView.as_view(), name="ticket-intervention-create"),
    path(
        "tickets/<int:ticket_pk>/interventions/<int:intervention_pk>/pdf/",
        TicketInterventionPdfView.as_view(),
        name="ticket-intervention-pdf",
    ),
    path("tickets/<int:pk>/agentic-resolution/", TicketAgenticResolutionView.as_view(), name="ticket-agentic-web"),
    path("tickets/<int:pk>/run-automation/", TicketAutomationRunView.as_view(), name="ticket-automation-web"),
    path("tickets/<int:pk>/credit-account/", TicketCreditAccountView.as_view(), name="ticket-credit-account"),
    path("products/", ProductListView.as_view(), name="product-list"),
    path("products/new/", ProductCreateView.as_view(), name="product-create"),
    path("products/<int:pk>/edit/", ProductUpdateView.as_view(), name="product-update"),
    path("products/<int:pk>/delete/", ProductDeleteView.as_view(), name="product-delete"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="product-detail"),
    path("products/<int:pk>/predictive-analysis/", ProductPredictiveAnalysisView.as_view(), name="product-predictive-web"),
    path("alerts/", PredictiveAlertListView.as_view(), name="alert-list"),
    path("knowledge/", KnowledgeArticleListView.as_view(), name="knowledge-list"),
    path("knowledge/<slug:slug>/", KnowledgeArticleDetailView.as_view(), name="knowledge-detail"),
    path("notifications/", NotificationListView.as_view(), name="notifications"),
    path("notifications/<int:pk>/read/", NotificationMarkReadView.as_view(), name="notification-read"),
    path("analytics/", AnalyticsPageView.as_view(), name="analytics-page"),
]
