# Generated by Django 4.2.11 on 2026-04-04 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('trigger_event', models.CharField(choices=[('ticket_created', 'Ticket cree'), ('ticket_updated', 'Ticket mis a jour'), ('ticket_overdue', 'Ticket en retard'), ('predictive_alert_created', 'Alerte predictive'), ('manual_run', 'Execution manuelle')], default='manual_run', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('actions', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='ai_summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Telephone'), ('chat', 'Chat'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('social', 'Reseaux sociaux'), ('portal', 'Portail client'), ('ar', 'Session AR')], default='portal', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Entrant'), ('outbound', 'Sortant'), ('internal', 'Interne')], default='inbound', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='sentiment_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='health_score',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='iot_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Succes'), ('failed', 'Echec'), ('skipped', 'Ignore')], default='success', max_length=20)),
                ('trigger_event', models.CharField(max_length=50)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='sav.automationrule')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_executions', to='sav.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_type', models.CharField(choices=[('video', 'Visio'), ('ar', 'Realite augmentee')], default='video', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Planifiee'), ('live', 'En direct'), ('completed', 'Terminee'), ('cancelled', 'Annulee')], default='scheduled', max_length=20)),
                ('meeting_link', models.URLField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('annotations_summary', models.TextField(blank=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['agent', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_support_sessions', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='support_sessions', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_sessions', to='sav.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(choices=[('iot', 'Capteur IoT'), ('manual', 'Saisie manuelle'), ('import', 'Import')], default='iot', max_length=20)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='sav.product')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictiveAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('anomaly', 'Anomalie'), ('maintenance', 'Maintenance'), ('warranty', 'Fin de garantie'), ('repeat_failure', 'Panne recurrente')], default='anomaly', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('in_progress', 'En traitement'), ('resolved', 'Resolue'), ('dismissed', 'Ignoree')], default='open', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('metric_name', models.CharField(blank=True, max_length=100)),
                ('metric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('predicted_failure_at', models.DateTimeField(blank=True, null=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictive_alerts', to='sav.product')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictive_alerts', to='sav.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('warranty_extension', 'Extension de garantie'), ('maintenance_contract', 'Contrat de maintenance'), ('spare_part', 'Piece detachee'), ('upgrade', 'Mise a niveau'), ('premium_support', 'Support premium')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rationale', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('proposed', 'Proposee'), ('accepted', 'Acceptee'), ('rejected', 'Refusee'), ('expired', 'Expiree')], default='proposed', max_length=20)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='sav.product')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='sav.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push'), ('in_app', 'In-app')], default='in_app', max_length=20)),
                ('event_type', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyee'), ('read', 'Lue'), ('failed', 'Echouee')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sav.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publie')], default='draft', max_length=20)),
                ('audience', models.CharField(choices=[('public', 'Clients'), ('internal', 'Interne')], default='public', max_length=20)),
                ('helpful_votes', models.PositiveIntegerField(default=0)),
                ('unhelpful_votes', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles', to='sav.product')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('human', 'Humain'), ('ai', 'IA'), ('system', 'Systeme')], default='human', max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('target_model', models.CharField(max_length=100)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_reference', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('triage', 'Qualification'), ('diagnosis', 'Diagnostic'), ('auto_resolution', 'Resolution automatique'), ('offer_generation', "Generation d'offres"), ('predictive_analysis', 'Analyse predictive'), ('insight_summary', 'Synthese client')], max_length=30)),
                ('status', models.CharField(choices=[('suggested', 'Suggeree'), ('executed', 'Executee'), ('rejected', 'Rejetee'), ('error', 'Erreur')], default='suggested', max_length=20)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rationale', models.TextField()),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('output_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ai_actions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_actions', to='sav.product')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_actions', to='sav.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
