# Generated by Django 4.2.11 on 2026-04-04 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0002_automationrule_message_ai_summary_message_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='suspected_fraud',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DeviceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=512, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web'), ('desktop', 'Desktop')], max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at', '-updated_at'],
            },
        ),
    ]
