# Generated by Django 4.2.11 on 2026-04-04 19:58

import uuid
from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def _unique_slug(label, existing_slugs):
    base_slug = slugify(label) or uuid.uuid4().hex[:8]
    slug = base_slug
    suffix = 2
    while slug in existing_slugs:
        slug = f"{base_slug}-{suffix}"
        suffix += 1
    existing_slugs.add(slug)
    return slug


def populate_organizations(apps, schema_editor):
    Organization = apps.get_model("sav", "Organization")
    User = apps.get_model("sav", "User")
    Product = apps.get_model("sav", "Product")
    Ticket = apps.get_model("sav", "Ticket")
    SupportSession = apps.get_model("sav", "SupportSession")
    KnowledgeArticle = apps.get_model("sav", "KnowledgeArticle")
    Notification = apps.get_model("sav", "Notification")
    OfferRecommendation = apps.get_model("sav", "OfferRecommendation")
    AIActionLog = apps.get_model("sav", "AIActionLog")
    WorkflowExecution = apps.get_model("sav", "WorkflowExecution")
    AuditLog = apps.get_model("sav", "AuditLog")

    existing_slugs = set(Organization.objects.values_list("slug", flat=True))
    organizations_by_label = {}

    def ensure_organization(label):
        normalized_label = (label or "").strip() or "Compte standard"
        organization = organizations_by_label.get(normalized_label)
        if organization is not None:
            return organization
        organization = Organization.objects.create(
            name=normalized_label,
            brand_name=normalized_label,
            slug=_unique_slug(normalized_label, existing_slugs),
            portal_tagline="Portail SAV dedie",
        )
        organizations_by_label[normalized_label] = organization
        return organization

    for client in User.objects.filter(role="client").order_by("id"):
        full_name = " ".join(part for part in [client.first_name, client.last_name] if part).strip()
        label = client.company_name or full_name or client.username
        organization = ensure_organization(label)
        update_fields = {"organization_id": organization.id}
        if not client.company_name:
            update_fields["company_name"] = organization.brand_name
        User.objects.filter(pk=client.pk).update(**update_fields)

    for product in Product.objects.exclude(client__organization__isnull=True).order_by("id"):
        Product.objects.filter(pk=product.pk).update(organization_id=product.client.organization_id)

    for ticket in Ticket.objects.order_by("id"):
        organization_id = ticket.client.organization_id if ticket.client_id else None
        if organization_id is None and ticket.product_id:
            organization_id = ticket.product.organization_id
        if organization_id:
            Ticket.objects.filter(pk=ticket.pk).update(organization_id=organization_id)

    for session in SupportSession.objects.order_by("id"):
        organization_id = session.ticket.organization_id if session.ticket_id else None
        if organization_id is None and session.client_id:
            organization_id = session.client.organization_id
        if organization_id:
            SupportSession.objects.filter(pk=session.pk).update(organization_id=organization_id)

    for article in KnowledgeArticle.objects.exclude(product__organization__isnull=True).order_by("id"):
        KnowledgeArticle.objects.filter(pk=article.pk).update(organization_id=article.product.organization_id)

    for notification in Notification.objects.order_by("id"):
        organization_id = notification.ticket.organization_id if notification.ticket_id else None
        if organization_id is None and notification.recipient_id:
            organization_id = notification.recipient.organization_id
        if organization_id:
            Notification.objects.filter(pk=notification.pk).update(organization_id=organization_id)

    for offer in OfferRecommendation.objects.order_by("id"):
        organization_id = offer.client.organization_id if offer.client_id else None
        if organization_id is None and offer.ticket_id:
            organization_id = offer.ticket.organization_id
        if organization_id is None and offer.product_id:
            organization_id = offer.product.organization_id
        if organization_id:
            OfferRecommendation.objects.filter(pk=offer.pk).update(organization_id=organization_id)

    for ai_action in AIActionLog.objects.order_by("id"):
        organization_id = ai_action.ticket.organization_id if ai_action.ticket_id else None
        if organization_id is None and ai_action.product_id:
            organization_id = ai_action.product.organization_id
        if organization_id:
            AIActionLog.objects.filter(pk=ai_action.pk).update(organization_id=organization_id)

    for execution in WorkflowExecution.objects.order_by("id"):
        organization_id = execution.ticket.organization_id if execution.ticket_id else None
        if organization_id is None and execution.rule_id:
            organization_id = execution.rule.organization_id
        if organization_id:
            WorkflowExecution.objects.filter(pk=execution.pk).update(organization_id=organization_id)

    for user in User.objects.exclude(role="client").filter(organization__isnull=True).order_by("id"):
        organization_ids = set(
            Ticket.objects.filter(assigned_agent_id=user.pk)
            .exclude(organization__isnull=True)
            .values_list("organization_id", flat=True)
        )
        organization_ids.update(
            SupportSession.objects.filter(agent_id=user.pk)
            .exclude(organization__isnull=True)
            .values_list("organization_id", flat=True)
        )
        if len(organization_ids) == 1:
            User.objects.filter(pk=user.pk).update(organization_id=organization_ids.pop())

    for audit_log in AuditLog.objects.filter(organization__isnull=True, actor__organization__isnull=False).order_by("id"):
        AuditLog.objects.filter(pk=audit_log.pk).update(organization_id=audit_log.actor.organization_id)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0003_ticket_suspected_fraud_deviceregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('portal_tagline', models.CharField(blank=True, max_length=255)),
                ('primary_color', models.CharField(default='#D5671D', max_length=7)),
                ('accent_color', models.CharField(default='#1C7A6A', max_length=7)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='aiactionlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_actions', to='sav.organization'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='sav.organization'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rules', to='sav.organization'),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles', to='sav.organization'),
        ),
        migrations.AddField(
            model_name='notification',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='sav.organization'),
        ),
        migrations.AddField(
            model_name='offerrecommendation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='sav.organization'),
        ),
        migrations.AddField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='sav.organization'),
        ),
        migrations.AddField(
            model_name='supportsession',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_sessions', to='sav.organization'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='sav.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='sav.organization'),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_executions', to='sav.organization'),
        ),
        migrations.RunPython(populate_organizations, noop_reverse),
    ]
