# Generated by Django 4.2.11 on 2026-04-04 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0005_ticketattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='XAF', max_length=10)),
                ('reason', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('executed', 'Execute'), ('cancelled', 'Annule')], default='executed', max_length=20)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_account_credits', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_account_credits', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_credits', to='sav.organization')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_credits', to='sav.ticket')),
            ],
            options={
                'ordering': ['-executed_at', '-created_at'],
            },
        ),
    ]
