# Generated by Django 4.2.11 on 2026-04-06 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sav", "0006_accountcredit"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("breakdown", "Panne"),
                    ("installation", "Installation"),
                    ("maintenance", "Maintenance"),
                    ("return", "Retour"),
                    ("refund", "Remboursement"),
                    ("complaint", "Reclamation"),
                    ("payment", "Paiement"),
                    ("withdrawal", "Retrait"),
                    ("bug", "Bug"),
                    ("account", "Compte"),
                ],
                default="breakdown",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TicketFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "client",
                    models.ForeignKey(
                        limit_choices_to={"role": "client"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_feedbacks",
                        to="sav.organization",
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="sav.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancialTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_reference",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=120)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Depot"),
                            ("withdrawal", "Retrait"),
                            ("payment", "Paiement"),
                            ("transfer", "Transfert"),
                            ("refund", "Remboursement"),
                            ("adjustment", "Ajustement"),
                        ],
                        default="payment",
                        max_length=20,
                    ),
                ),
                (
                    "ledger_side",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        default="debit",
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="XAF", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("completed", "Completee"),
                            ("failed", "Echouee"),
                            ("disputed", "Contestee"),
                            ("blocked", "Bloquee"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("suspected_fraud", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "client",
                    models.ForeignKey(
                        limit_choices_to={"role": "client"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_transactions",
                        to="sav.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="related_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="sav.financialtransaction",
            ),
        ),
    ]
