# Generated by Django 4.2.11 on 2026-04-06 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_ticket_statuses(apps, schema_editor):
    Ticket = apps.get_model("sav", "Ticket")
    status_map = {
        "triaged": "assigned",
        "scheduled": "assigned",
        "waiting_customer": "waiting",
        "waiting_parts": "waiting",
    }
    for old_status, new_status in status_map.items():
        Ticket.objects.filter(status=old_status).update(status=new_status)


class Migration(migrations.Migration):

    dependencies = [
        ("sav", "0007_user_is_verified_alter_ticket_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="business_domain",
            field=models.CharField(
                choices=[
                    ("it", "Informatique"),
                    ("cooling", "Froid & Climatisation"),
                    ("generator", "Groupe electrogene"),
                    ("video", "Videosurveillance"),
                    ("other", "Autre"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="agent",
            field=models.ForeignKey(
                limit_choices_to={
                    "role__in": (
                        "support",
                        "technician",
                        "head_sav",
                        "admin",
                        "agent",
                        "manager",
                    )
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interventions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="supportsession",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "role__in": (
                        "support",
                        "technician",
                        "head_sav",
                        "admin",
                        "agent",
                        "manager",
                    )
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handled_support_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="assigned_agent",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "role__in": (
                        "support",
                        "technician",
                        "head_sav",
                        "admin",
                        "agent",
                        "manager",
                    )
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="channel",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("phone", "Telephone"),
                    ("whatsapp", "WhatsApp"),
                    ("web", "Portail web"),
                    ("api", "API"),
                    ("on_site", "Visite"),
                ],
                default="web",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Nouveau"),
                    ("assigned", "Assigne"),
                    ("in_progress", "En cours"),
                    ("waiting", "En attente"),
                    ("resolved", "Resolue"),
                    ("closed", "Ferme"),
                    ("cancelled", "Annule"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("support", "Agent support / Hotliner"),
                    ("technician", "Technicien"),
                    ("head_sav", "Responsable SAV"),
                    ("auditor", "Auditeur / Direction"),
                    ("admin", "Administrateur"),
                    ("agent", "Agent SAV (legacy)"),
                    ("manager", "Manager SAV (legacy)"),
                ],
                default="client",
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate_ticket_statuses, migrations.RunPython.noop),
    ]
