# Generated by Django 4.2.11 on 2026-04-07 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sav", "0008_ticket_business_domain_ticket_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="client_signature_file",
            field=models.FileField(
                blank=True, upload_to="interventions/signatures/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="client_signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="intervention",
            name="client_signed_by",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="intervention",
            name="location_snapshot",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="intervention",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interventions",
                to="sav.organization",
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="report_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="intervention",
            name="report_pdf",
            field=models.FileField(
                blank=True, upload_to="interventions/reports/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="structured_parts_used",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="intervention",
            name="technical_report",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="intervention",
            name="time_spent_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="organization",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="organization",
            name="country",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="organization",
            name="headquarters_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="reporting_emails",
            field=models.TextField(
                blank=True,
                help_text="Liste d'emails separes par des virgules pour les rapports automatiques.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="product",
            name="contract_reference",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="product",
            name="counter_bw",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="counter_color",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="counter_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="detailed_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="equipment_photo",
            field=models.FileField(blank=True, upload_to="products/photos/%Y/%m/%d/"),
        ),
        migrations.AddField(
            model_name="product",
            name="equipment_type",
            field=models.CharField(
                choices=[
                    ("copier", "Copieur"),
                    ("printer", "Imprimante"),
                    ("aircon", "Climatiseur"),
                    ("generator", "Groupe electrogene"),
                    ("camera", "Camera"),
                    ("other", "Autre"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="installation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="model_reference",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="client_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Actif"),
                    ("inactive", "Inactif"),
                    ("prospect", "Prospect"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="client_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("enterprise", "Entreprise"),
                    ("individual", "Particulier"),
                    ("administration", "Administration"),
                ],
                default="enterprise",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="internal_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="primary_city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="user",
            name="primary_region",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="user",
            name="professional_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.FileField(
                blank=True, upload_to="users/profile_photos/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sector",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="user",
            name="specialties",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="tax_identifier",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="user",
            name="technician_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("available", "Disponible"),
                    ("on_site", "En intervention"),
                    ("on_leave", "En conge"),
                    ("unavailable", "Indisponible"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="weekly_availability",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="InterventionMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("before", "Avant intervention"),
                            ("during", "Pendant intervention"),
                            ("after", "Apres intervention"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="interventions/media/%Y/%m/%d/")),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="sav.intervention",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intervention_media",
                        to="sav.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intervention_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ClientContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("job_title", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_primary", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        limit_choices_to={"role": "client"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_contacts",
                        to="sav.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "first_name", "last_name", "id"],
            },
        ),
    ]
