# Generated by Codex on 2026-04-14

from django.db import migrations


def grant_staff_to_admin_role_users(apps, schema_editor):
    User = apps.get_model("sav", "User")
    User.objects.filter(role="admin", is_staff=False).update(is_staff=True)


class Migration(migrations.Migration):

    dependencies = [
        ("sav", "0011_auditlog_http_method_auditlog_request_path_and_more"),
    ]

    operations = [
        migrations.RunPython(grant_staff_to_admin_role_users, migrations.RunPython.noop),
    ]
