# Generated by Django 4.2.11 on 2026-04-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0012_admin_role_grants_staff_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='product_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('support', 'Agent support (Niveau 1 / Hotliner)'), ('technician', 'Agent technique (Niveau 2)'), ('expert', 'Chef technicien / Expert (Niveau 3)'), ('supervisor', 'Superviseur / Team Leader'), ('qa', 'Qualite / QA SAV'), ('dispatcher', 'Planificateur / Dispatch'), ('field_technician', 'Technicien terrain'), ('vip_support', 'Support VIP / Grands comptes'), ('system_bot', 'Systeme automatique (IA / Bot)'), ('head_sav', 'Responsable SAV'), ('auditor', 'Auditeur / Direction'), ('admin', 'Administrateur'), ('agent', 'Agent support (legacy)'), ('manager', 'Responsable SAV (legacy)')], default='client', max_length=20),
        ),
    ]
