# Generated by Django 4.2.11 on 2026-04-18 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0013_ticket_product_label_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'role__in': ('support', 'agent', 'vip_support', 'technician', 'expert', 'field_technician')}, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportsession',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ('support', 'agent', 'vip_support', 'technician', 'expert', 'field_technician')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_support_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ('support', 'agent', 'vip_support', 'technician', 'expert', 'field_technician')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketassignment',
            name='technician',
            field=models.ForeignKey(limit_choices_to={'role__in': ('support', 'agent', 'vip_support', 'technician', 'expert', 'field_technician')}, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
