# Generated by Django 4.2.11 on 2026-04-23 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sav", "0014_alter_intervention_agent_alter_supportsession_agent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervention",
            name="agent",
            field=models.ForeignKey(
                limit_choices_to={
                    "role__in": (
                        "support",
                        "agent",
                        "vip_support",
                        "technician",
                        "expert",
                        "field_technician",
                        "cfao_manager",
                        "cfao_works",
                        "hvac_manager",
                        "software_owner",
                    )
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interventions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="supportsession",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "role__in": (
                        "support",
                        "agent",
                        "vip_support",
                        "technician",
                        "expert",
                        "field_technician",
                        "cfao_manager",
                        "cfao_works",
                        "hvac_manager",
                        "software_owner",
                    )
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handled_support_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="assigned_agent",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "role__in": (
                        "support",
                        "agent",
                        "vip_support",
                        "technician",
                        "expert",
                        "field_technician",
                        "cfao_manager",
                        "cfao_works",
                        "hvac_manager",
                        "software_owner",
                    )
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ticketassignment",
            name="technician",
            field=models.ForeignKey(
                limit_choices_to={
                    "role__in": (
                        "support",
                        "agent",
                        "vip_support",
                        "technician",
                        "expert",
                        "field_technician",
                        "cfao_manager",
                        "cfao_works",
                        "hvac_manager",
                        "software_owner",
                    )
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("support", "Agent support (Niveau 1 / Hotliner)"),
                    ("technician", "Agent technique (Niveau 2)"),
                    ("expert", "Chef technicien / Expert (Niveau 3)"),
                    ("cfao_manager", "Responsable CFAO / GTC & dessin technique"),
                    ("cfao_works", "Conducteur de travaux CFAO"),
                    ("hvac_manager", "Responsable froid & climatisation"),
                    ("software_owner", "Gestionnaire principal du logiciel"),
                    ("supervisor", "Superviseur / Team Leader"),
                    ("qa", "Qualite / QA SAV"),
                    ("dispatcher", "Planificateur / Dispatch"),
                    ("field_technician", "Technicien terrain"),
                    ("vip_support", "Support VIP / Grands comptes"),
                    ("system_bot", "Systeme automatique (IA / Bot)"),
                    ("head_sav", "Responsable SAV"),
                    ("auditor", "Auditeur / Direction"),
                    ("admin", "Administrateur"),
                    ("agent", "Agent support (legacy)"),
                    ("manager", "Responsable SAV (legacy)"),
                ],
                default="client",
                max_length=20,
            ),
        ),
    ]
