# Generated by Django 6.0.4 on 2026-04-28 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def backfill_creator_and_merge_field_technicians(apps, schema_editor):
    User = apps.get_model("sav", "User")
    Ticket = apps.get_model("sav", "Ticket")
    User.objects.filter(role="field_technician").update(role="technician")
    Ticket.objects.filter(created_by__isnull=True).update(created_by=F("client"))


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0015_expand_specialist_roles_and_escalation_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_creator_and_merge_field_technicians, noop_reverse),
        migrations.AlterField(
            model_name='intervention',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'role__in': ('support', 'agent', 'vip_support', 'technician')}, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportsession',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ('support', 'agent', 'vip_support', 'technician')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_support_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ('support', 'agent', 'vip_support', 'technician')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('breakdown', 'Panne'), ('installation', 'Installation'), ('maintenance', 'Maintenance'), ('complaint', 'Reclamation'), ('payment', 'Paiement'), ('bug', 'Bug'), ('account', 'Compte')], default='breakdown', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketassignment',
            name='technician',
            field=models.ForeignKey(limit_choices_to={'role__in': ('support', 'agent', 'vip_support', 'technician')}, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('support', 'Agent support (Niveau 1 / Hotliner)'), ('technician', 'Agent technique (Niveau 2)'), ('expert', 'Chef technicien / Expert (Niveau 3)'), ('cfao_manager', 'Responsable CFAO / GTC & dessin technique'), ('cfao_works', 'Conducteur de travaux CFAO'), ('hvac_manager', 'Responsable froid & climatisation'), ('software_owner', 'Gestionnaire principal du logiciel'), ('supervisor', 'Superviseur / Team Leader'), ('qa', 'Qualite / QA SAV'), ('dispatcher', 'Planificateur / Dispatch'), ('vip_support', 'Support VIP / Grands comptes'), ('system_bot', 'Systeme automatique (IA / Bot)'), ('head_sav', 'Responsable SAV'), ('auditor', 'Auditeur / Direction'), ('admin', 'Administrateur'), ('agent', 'Agent support (legacy)'), ('manager', 'Responsable SAV (legacy)')], default='client', max_length=20),
        ),
    ]
