# Generated by Django 6.0.4 on 2026-04-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0016_ticket_created_by_alter_intervention_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('qualification', 'Qualification en cours'), ('pending_customer', 'En attente client'), ('assigned', 'Assigne'), ('in_progress', 'En cours'), ('in_progress_n1', 'En traitement (N1)'), ('in_progress_n2', 'En traitement (N2)'), ('expertise', 'Expertise en cours'), ('intervention_planned', 'Intervention planifiee'), ('intervention_done', 'Intervention realisee'), ('qa_control', 'En controle qualite'), ('pending_client_confirmation', 'En attente confirmation client'), ('waiting', 'En attente'), ('resolved', 'Resolue'), ('closed', 'Ferme'), ('cancelled', 'Annule')], default='new', max_length=32),
        ),
    ]
