# Generated by Django 4.2.7 on 2026-04-30 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def normalize_removed_choices(apps, schema_editor):
    Ticket = apps.get_model("sav", "Ticket")
    FinancialTransaction = apps.get_model("sav", "FinancialTransaction")
    Ticket.objects.filter(
        category__in=["complaint", "payment", "account", "return", "refund", "withdrawal"]
    ).update(category="breakdown")
    FinancialTransaction.objects.filter(transaction_type="transfer").update(transaction_type="adjustment")


class Migration(migrations.Migration):

    dependencies = [
        ("sav", "0017_alter_ticket_status"),
    ]

    operations = [
        migrations.RunPython(normalize_removed_choices, migrations.RunPython.noop),
        migrations.AddField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="financialtransaction",
            name="suspected_fraud",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="related_transaction",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="suspected_fraud",
        ),
        migrations.RemoveField(
            model_name="intervention",
            name="cost",
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Depot"),
                    ("withdrawal", "Retrait"),
                    ("payment", "Paiement"),
                    ("refund", "Remboursement"),
                    ("adjustment", "Ajustement"),
                ],
                default="payment",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="agent",
            field=models.ForeignKey(
                limit_choices_to={
                    "role__in": (
                        "support",
                        "manager",
                        "head_sav",
                        "software_owner",
                        "supervisor",
                        "qa",
                        "dispatcher",
                        "vip_support",
                        "agent",
                        "technician",
                    )
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interventions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="supportsession",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "role__in": (
                        "support",
                        "manager",
                        "head_sav",
                        "software_owner",
                        "supervisor",
                        "qa",
                        "dispatcher",
                        "vip_support",
                        "agent",
                        "technician",
                    )
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handled_support_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="assigned_agent",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "role__in": (
                        "support",
                        "manager",
                        "head_sav",
                        "software_owner",
                        "supervisor",
                        "qa",
                        "dispatcher",
                        "vip_support",
                        "agent",
                        "technician",
                    )
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("breakdown", "Panne"),
                    ("installation", "Installation"),
                    ("maintenance", "Maintenance"),
                    ("bug", "Bug"),
                ],
                default="breakdown",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticketassignment",
            name="technician",
            field=models.ForeignKey(
                limit_choices_to={
                    "role__in": (
                        "support",
                        "manager",
                        "head_sav",
                        "software_owner",
                        "supervisor",
                        "qa",
                        "dispatcher",
                        "vip_support",
                        "agent",
                        "technician",
                    )
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
