# Generated by Django 6.0.4 on 2026-05-04 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0021_restore_field_technician_delegation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'role__in': ('cfao_manager', 'cfao_works', 'hvac_manager', 'chief_technician', 'technician')}, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportsession',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ('cfao_manager', 'cfao_works', 'hvac_manager', 'chief_technician', 'technician')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_support_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ('cfao_manager', 'cfao_works', 'hvac_manager', 'chief_technician', 'technician')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketassignment',
            name='technician',
            field=models.ForeignKey(limit_choices_to={'role__in': ('cfao_manager', 'cfao_works', 'hvac_manager', 'chief_technician', 'technician')}, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
