# Generated by Django 6.0.5 on 2026-05-12 12:21

import django.db.models.deletion
import sav.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0022_alter_intervention_agent_alter_supportsession_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('service', models.CharField(choices=[('it', 'SAV Informatique'), ('cfao', 'SAV CFAO'), ('generator', 'SAV Groupe electrogene'), ('cooling', 'SAV Froid & Climatisation'), ('other', 'Autre service')], default='it', max_length=20)),
                ('period_type', models.CharField(choices=[('monthly', 'Mensuelle'), ('quarterly', 'Trimestrielle')], default='monthly', max_length=20)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quarter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField(default=sav.models._current_year)),
                ('task_lines', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publie'), ('archived', 'Archive')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_programs', to='sav.organization')),
                ('responsible', models.ForeignKey(blank=True, limit_choices_to={'role__in': ('head_sav', 'admin', 'manager', 'cfao_manager', 'cfao_works', 'hvac_manager', 'chief_technician')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-quarter', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('service', models.CharField(choices=[('it', 'SAV Informatique'), ('cfao', 'SAV CFAO'), ('generator', 'SAV Groupe electrogene'), ('cooling', 'SAV Froid & Climatisation'), ('other', 'Autre service')], default='it', max_length=20)),
                ('periodicity', models.CharField(choices=[('monthly', 'Mensuelle'), ('quarterly', 'Trimestrielle'), ('semiannual', 'Semestrielle'), ('annual', 'Annuelle')], default='monthly', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planifie'), ('notified', 'Notifie'), ('in_progress', 'En cours'), ('done', 'Termine'), ('postponed', 'Reporte'), ('anomaly_detected', 'Anomalie detectee'), ('cancelled', 'Annule')], default='planned', max_length=24)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('instructions', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normale'), ('high', 'Haute'), ('critical', 'Critique')], default='normal', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('postponed_to', models.DateField(blank=True, null=True)),
                ('postponement_reason', models.TextField(blank=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('overdue_alerted_at', models.DateTimeField(blank=True, null=True)),
                ('anomaly_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_maintenance_tickets', to='sav.ticket')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_maintenance_tickets', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tickets', to='sav.organization')),
                ('products', models.ManyToManyField(blank=True, related_name='maintenance_tickets', to='sav.product')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='sav.maintenanceprogram')),
                ('responsible', models.ForeignKey(blank=True, limit_choices_to={'role__in': ('head_sav', 'admin', 'manager', 'cfao_manager', 'cfao_works', 'hvac_manager', 'chief_technician')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_maintenance_tickets', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(limit_choices_to={'role__in': ('cfao_manager', 'cfao_works', 'hvac_manager', 'chief_technician', 'technician')}, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_date', 'priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_started_at', models.DateTimeField()),
                ('actual_finished_at', models.DateTimeField()),
                ('checklist_completed', models.JSONField(blank=True, default=list)),
                ('observations', models.TextField()),
                ('parts_used', models.TextField(blank=True)),
                ('anomaly_detected', models.BooleanField(default=False)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('client_signed_by', models.CharField(blank=True, max_length=255)),
                ('client_signature_file', models.FileField(blank=True, upload_to='maintenance/signatures/%Y/%m/%d/')),
                ('final_status', models.CharField(choices=[('done', 'Termine'), ('postponed', 'Reporte'), ('anomaly_detected', 'Anomalie detectee')], default='done', max_length=24)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_reports', to='sav.organization')),
                ('technician', models.ForeignKey(limit_choices_to={'role__in': ('cfao_manager', 'cfao_works', 'hvac_manager', 'chief_technician', 'technician')}, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reports', to=settings.AUTH_USER_MODEL)),
                ('maintenance_ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='sav.maintenanceticket')),
            ],
            options={
                'ordering': ['-actual_finished_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(choices=[('it', 'SAV Informatique'), ('cfao', 'SAV CFAO'), ('generator', 'SAV Groupe electrogene'), ('cooling', 'SAV Froid & Climatisation'), ('other', 'Autre service')], default='it', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('equipment_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates', to='sav.equipmentcategory')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates', to='sav.organization')),
            ],
            options={
                'ordering': ['service', 'name'],
                'unique_together': {('organization', 'service', 'equipment_category', 'name')},
            },
        ),
    ]
