# Generated by Django 6.0.5 on 2026-05-19 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_initial_scheduled_date(apps, schema_editor):
    MaintenanceTicket = apps.get_model("sav", "MaintenanceTicket")
    MaintenanceTicket.objects.filter(initial_scheduled_date__isnull=True).update(initial_scheduled_date=models.F("scheduled_date"))


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0023_maintenanceprogram_maintenanceticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='report_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='report_pdf',
            field=models.FileField(blank=True, upload_to='maintenance/reports/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='initial_scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MaintenanceReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='maintenance/photos/%Y/%m/%d/')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_report_photos', to='sav.organization')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_files', to='sav.maintenancereport')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_report_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.RunPython(backfill_initial_scheduled_date, migrations.RunPython.noop),
    ]
