# Generated by Django 6.0.5 on 2026-05-19 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0024_maintenancereport_report_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_maintenance_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
