# Generated by Django 6.0.5 on 2026-05-21 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0025_maintenancereport_validated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'role__in': ('support', 'agent', 'dispatcher', 'vip_support', 'supervisor', 'cfao_manager', 'cfao_works', 'hvac_manager', 'chief_technician', 'technician')}, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenanceprogram',
            name='responsible',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ('head_sav', 'admin', 'manager', 'cfao_manager', 'cfao_works', 'hvac_manager', 'chief_technician')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='technician',
            field=models.ForeignKey(limit_choices_to={'role__in': ('cfao_manager', 'cfao_works', 'hvac_manager', 'chief_technician', 'technician')}, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='responsible',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ('head_sav', 'admin', 'manager', 'cfao_manager', 'cfao_works', 'hvac_manager', 'chief_technician')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_maintenance_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='technician',
            field=models.ForeignKey(limit_choices_to={'role__in': ('cfao_manager', 'cfao_works', 'hvac_manager', 'chief_technician', 'technician')}, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportsession',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ('support', 'agent', 'dispatcher', 'vip_support', 'supervisor', 'cfao_manager', 'cfao_works', 'hvac_manager', 'chief_technician', 'technician')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_support_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ('support', 'agent', 'dispatcher', 'vip_support', 'supervisor', 'cfao_manager', 'cfao_works', 'hvac_manager', 'chief_technician', 'technician')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketassignment',
            name='technician',
            field=models.ForeignKey(limit_choices_to={'role__in': ('support', 'agent', 'dispatcher', 'vip_support', 'supervisor', 'cfao_manager', 'cfao_works', 'hvac_manager', 'chief_technician', 'technician')}, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('head_sav', 'Responsable SAV'), ('support', 'Agent support / Hotliner'), ('cfao_manager', 'Responsable CFAO / Responsable de Projet Technique CFAO'), ('cfao_works', 'Conducteur de travaux CFAO'), ('hvac_manager', 'Responsable Froid et climatisation / Responsable technique froid'), ('chief_technician', 'Chef Technicien Froid & Climatisation'), ('technician', 'Technicien de maintenance'), ('client', 'Client'), ('auditor', 'Auditeur / Direction')], default='client', max_length=20),
        ),
    ]
