# Generated by Django 6.0.5 on 2026-05-23 09:51

from django.db import migrations, models


def normalize_legacy_product_statuses(apps, schema_editor):
    Product = apps.get_model("sav", "Product")
    Product.objects.filter(status__in=["active", "in_service"]).update(status="operational")
    Product.objects.filter(status__in=["replaced", "retired"]).update(status="out_of_service")


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0026_alter_intervention_agent_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_legacy_product_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('operational', 'Operationnel'), ('broken', 'En panne'), ('maintenance', 'En maintenance'), ('out_of_service', 'Hors service')], default='operational', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='business_domain',
            field=models.CharField(choices=[('it', 'Informatique'), ('monetics', 'Monetique'), ('cfao', 'CFAO'), ('cooling', 'Froid & Climatisation'), ('generator', 'Groupe electrogene'), ('video', 'Videosurveillance'), ('geolocation', 'Geolocalisation'), ('other', 'Autre')], default='other', max_length=20),
        ),
    ]
