# Generated by Django 6.0.5 on 2026-05-24 14:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0027_align_cdc_v3_equipment_and_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='business_domain',
            field=models.CharField(choices=[('it', 'Informatique'), ('monetics', 'Monetique'), ('cfao', 'CFAO'), ('cooling', 'Froid & Climatisation'), ('generator', 'Groupe electrogene'), ('video', 'Videosurveillance'), ('geolocation', 'Geolocalisation'), ('other', 'Autre')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='equipment_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles', to='sav.equipmentcategory'),
        ),
        migrations.AddField(
            model_name='organization',
            name='personal_data_access_logging_enabled',
            field=models.BooleanField(default=True, help_text='Journalise les consultations des fiches clients/equipements contenant des donnees personnelles.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='ticket_retention_years',
            field=models.PositiveSmallIntegerField(default=5, help_text='Duree de conservation active des tickets clos avant archivage logique.'),
        ),
        migrations.AddField(
            model_name='product',
            name='current_location_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='location_status',
            field=models.CharField(choices=[('installed', 'Installe chez le client'), ('workshop', 'En atelier'), ('transit', 'En transit'), ('storage', 'En stockage')], default='installed', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='archive_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('code', models.SlugField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='sav.organization')),
            ],
            options={
                'ordering': ['organization__name', 'city', 'name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='sav.agency'),
        ),
        migrations.CreateModel(
            name='ClientSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('code', models.SlugField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_sites', to='sav.agency')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_sites', to='sav.organization')),
            ],
            options={
                'ordering': ['client__company_name', 'client__username', '-is_primary', 'name'],
                'unique_together': {('client', 'code')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='sav.clientsite'),
        ),
        migrations.CreateModel(
            name='EquipmentLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_location', models.CharField(blank=True, max_length=255)),
                ('from_location_status', models.CharField(blank=True, choices=[('installed', 'Installe chez le client'), ('workshop', 'En atelier'), ('transit', 'En transit'), ('storage', 'En stockage')], max_length=20)),
                ('to_location', models.CharField(blank=True, max_length=255)),
                ('to_location_status', models.CharField(choices=[('installed', 'Installe chez le client'), ('workshop', 'En atelier'), ('transit', 'En transit'), ('storage', 'En stockage')], default='installed', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('moved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_client', models.ForeignKey(blank=True, limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_moves_from', to=settings.AUTH_USER_MODEL)),
                ('from_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_moves_from', to='sav.clientsite')),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_location_moves', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_location_history', to='sav.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='sav.product')),
                ('to_client', models.ForeignKey(blank=True, limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_moves_to', to=settings.AUTH_USER_MODEL)),
                ('to_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_moves_to', to='sav.clientsite')),
            ],
            options={
                'ordering': ['-moved_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfflineSyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='POST', max_length=10)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('applied', 'Synchronisee'), ('failed', 'Echec')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('client_created_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_sync_operations', to='sav.deviceregistration')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_sync_operations', to='sav.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_sync_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('reference', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(default='piece', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('equipment_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_parts', to='sav.equipmentcategory')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_parts', to='sav.organization')),
            ],
            options={
                'ordering': ['category', 'name', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_snapshot', models.CharField(blank=True, max_length=180)),
                ('reference_snapshot', models.CharField(blank=True, max_length=120)),
                ('category_snapshot', models.CharField(blank=True, max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_snapshot', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_part_usages', to='sav.organization')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_usages', to='sav.maintenancereport')),
                ('spare_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_usages', to='sav.sparepart')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InterventionPartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_snapshot', models.CharField(blank=True, max_length=180)),
                ('reference_snapshot', models.CharField(blank=True, max_length=120)),
                ('category_snapshot', models.CharField(blank=True, max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_snapshot', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_usages', to='sav.intervention')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervention_part_usages', to='sav.organization')),
                ('spare_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervention_usages', to='sav.sparepart')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='sparepart',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='sav_sparepart_unique_reference_per_organization'),
        ),
    ]
