# Generated by Django 6.0.5 on 2026-06-13 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0028_cdc_v3_operations_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='client_validated_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='client_validation_impossible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intervention',
            name='client_validation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='validation_impossible_photo',
            field=models.FileField(blank=True, upload_to='interventions/bypass/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='validation_impossible_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalation_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_team_intervention',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_escalation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_escalation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_team_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='member_team_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('assigned', 'Assigne'), ('planning_proposed', 'Planification proposee'), ('planned', 'Planifie'), ('start_requested', 'Demande de debut envoyee'), ('in_progress', 'En cours'), ('waiting_part', 'En attente de piece'), ('escalated', 'En escalade'), ('waiting_solution', 'En attente solution responsable'), ('finish_requested', 'Demande de fin envoyee'), ('done', 'Termine (travaux finis)'), ('resolved', 'Resolue (valide client)'), ('closed', 'Ferme'), ('cancelled', 'Annule'), ('reassign_required', 'A reassigner'), ('blocked_direction', 'Bloque - Direction')], default='new', max_length=32),
        ),
    ]
