# Generated by Codex on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sav", "0029_intervention_client_validated_start_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="client_validated_finish_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="status_before_escalation",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Nouveau"),
                    ("pending_assignment", "En attente d'assignation"),
                    ("assigned", "Assigne"),
                    ("team_pending", "En attente constitution equipe"),
                    ("team_ready", "Equipe constituee"),
                    ("planning_proposed", "Planification proposee"),
                    ("planned", "Planifie"),
                    ("start_requested", "Demande de debut envoyee"),
                    ("in_progress", "En cours"),
                    ("collective_in_progress", "Intervention collective"),
                    ("waiting_part", "En attente de piece"),
                    ("escalated", "En escalade"),
                    ("waiting_solution", "En attente solution responsable"),
                    ("finish_requested", "Demande de fin envoyee"),
                    ("done", "Termine"),
                    ("resolved", "Resolue (valide client)"),
                    ("closed", "Ferme"),
                    ("cancelled", "Annule"),
                    ("reassign_required", "A reassigner"),
                    ("reassigned", "Reassigne"),
                    ("blocked_direction", "Bloque - Direction"),
                ],
                default="new",
                max_length=32,
            ),
        ),
    ]
