# Generated by Django 6.0.5 on 2026-06-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0030_ticket_advanced_workflow_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceticket',
            name='initial_scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='postponed_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='scheduled_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('head_sav', 'Responsable SAV'), ('support', 'Agent support / Hotliner'), ('cfao_manager', 'Responsable CFAO / Responsable de Projet Technique CFAO'), ('cfao_works', 'Conducteur de travaux CFAO'), ('hvac_manager', 'Responsable Froid et climatisation / Responsable technique froid'), ('chief_technician', 'Chef Technicien Froid & Climatisation'), ('technician', 'Technicien de maintenance'), ('client', 'Client'), ('auditor', 'Auditeur / Direction')], default='client', max_length=20, verbose_name='Fonction'),
        ),
    ]
