# Generated by Django 6.0.5 on 2026-06-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0033_escalationhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalationhistory',
            options={'ordering': ['-created_at'], 'verbose_name': "Historique d'escalade", 'verbose_name_plural': "Historiques d'escalade"},
        ),
        migrations.AlterField(
            model_name='escalationhistory',
            name='action',
            field=models.CharField(choices=[('escalated', 'Escaladee'), ('reassigned', 'Reassignee a un autre technicien'), ('solution_provided', 'Solution fournie'), ('declined', 'Declinee par le responsable'), ('continued', 'Continuee apres solution')], help_text='Action prise par le responsable', max_length=30),
        ),
    ]
