# Generated by Django 6.0.5 on 2026-06-18 23:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0034_alter_escalationhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='team_members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ('cfao_manager', 'cfao_works', 'hvac_manager', 'chief_technician', 'technician')}, related_name='maintenance_team_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offerrecommendation',
            name='offer_type',
            field=models.CharField(choices=[('warranty_extension', 'Extension de garantie'), ('maintenance_contract', 'Contrat de maintenance'), ('spare_part', 'Piece detachee'), ('upgrade', 'Mise a niveau'), ('premium_support', 'Assistance premium')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('head_sav', 'Responsable SAV'), ('support', "Agent assistance / centre d'appels"), ('cfao_manager', 'Responsable CFAO / Responsable de Projet Technique CFAO'), ('cfao_works', 'Conducteur de travaux CFAO'), ('hvac_manager', 'Responsable Froid et climatisation / Responsable technique froid'), ('chief_technician', 'Chef Technicien Froid & Climatisation'), ('technician', 'Technicien de maintenance'), ('client', 'Client'), ('auditor', 'Auditeur / Direction')], default='client', max_length=20, verbose_name='Fonction'),
        ),
    ]
