# Generated by Django 6.0.5 on 2026-06-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0035_maintenanceticket_team_members_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['organization', 'agent', 'scheduled_for'], name='sav_interv_org_agent_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['ticket', 'created_at'], name='sav_interv_ticket_created_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['status', 'scheduled_for'], name='sav_interv_status_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceticket',
            index=models.Index(fields=['organization', 'status', 'scheduled_date'], name='sav_maint_org_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceticket',
            index=models.Index(fields=['technician', 'status', 'scheduled_date'], name='sav_maint_tech_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceticket',
            index=models.Index(fields=['client', 'scheduled_date'], name='sav_maint_client_date_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'status'], name='sav_notif_recipient_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'status'], name='sav_notif_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['channel', 'status'], name='sav_notif_channel_status_idx'),
        ),
        migrations.AddIndex(
            model_name='predictivealert',
            index=models.Index(fields=['status', 'severity'], name='sav_alert_status_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='predictivealert',
            index=models.Index(fields=['product', 'status'], name='sav_alert_product_status_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'status'], name='sav_product_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['client', 'status'], name='sav_product_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'warranty_end'], name='sav_product_org_warranty_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['organization', 'status'], name='sav_ticket_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['organization', 'priority'], name='sav_ticket_org_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['organization', 'created_at'], name='sav_ticket_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['organization', 'sla_deadline'], name='sav_ticket_org_sla_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['client', 'status'], name='sav_ticket_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_agent', 'status'], name='sav_ticket_agent_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'sla_deadline'], name='sav_ticket_status_sla_idx'),
        ),
    ]
