# Generated by Django 6.0.5 on 2026-06-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0036_intervention_sav_interv_org_agent_sched_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='deep_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivery_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='provider',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notification',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_daily_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 = illimite.'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_do_not_disturb_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_do_not_disturb_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_email_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_min_interval_minutes',
            field=models.PositiveIntegerField(default=0, help_text='0 = pas de limite.'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_push_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_sms_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_whatsapp_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('fr', 'Francais'), ('en', 'Anglais')], default='fr', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyee'), ('read', 'Lue'), ('clicked', 'Cliquee'), ('failed', 'Echouee')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event_type', 'created_at'], name='sav_notif_event_created_idx'),
        ),
    ]
