# Generated by Django 6.0.5 on 2026-06-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0037_notification_action_payload_notification_clicked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('pending_assignment', "En attente d'assignation"), ('assigned', 'Assigne'), ('team_pending', 'En attente constitution equipe'), ('team_ready', 'Equipe constituee'), ('planning_proposed', 'Planification proposee'), ('planned', 'Planifie'), ('start_requested', 'Demande de debut envoyee'), ('in_progress', 'En cours'), ('collective_in_progress', 'Intervention collective'), ('waiting_part', 'En attente de piece'), ('escalated', 'En escalade'), ('waiting_solution', 'En attente solution responsable'), ('waiting_diagnostic', 'En attente diagnostic'), ('finish_requested', 'Demande de fin envoyee'), ('done', 'Termine'), ('resolved', 'Resolue (valide client)'), ('closed', 'Ferme'), ('cancelled', 'Annule'), ('reassign_required', 'A reassigner'), ('reassigned', 'Reassigne'), ('blocked_direction', 'Bloque - Direction')], default='new', max_length=32),
        ),
    ]
