# Generated by Django 6.0.5 on 2026-07-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0038_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='intervention_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='parts_status',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='work_to_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='call_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='equipment_brand',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='equipment_identifier',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='equipment_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='intervention_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='overnight_stays',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='route',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='system_tools',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
