# Generated by Django 6.0.5 on 2026-07-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0039_maintenancereport_intervention_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='export_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Tableur XLSX'), ('csv', 'CSV')], default='pdf', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Notification mobile'), ('in_app', "Dans l'application")], default='in_app', max_length=20),
        ),
    ]
