# Generated by Django 6.0.5 on 2026-07-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0040_alter_generatedreport_export_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('fr', 'Francais')], default='fr', max_length=8),
        ),
    ]
