# Generated by Django 6.0.5 on 2026-07-19 20:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0041_alter_user_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='actual_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='maintenance_type',
            field=models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('predictive', 'Predictive'), ('inspection', 'Inspection'), ('control', 'Controle')], default='preventive', max_length=20),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='supplier',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
