# Generated by Django 6.0.5 on 2026-07-20 09:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0042_cmms_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceprogram',
            name='checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='maintenanceprogram',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenanceprogram',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceprogram',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_rules', to='sav.product'),
        ),
        migrations.AddField(
            model_name='maintenanceprogram',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='maintenanceprogram',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle'), ('quarterly', 'Trimestrielle'), ('semiannual', 'Semestrielle'), ('annual', 'Annuelle')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenanceprogram',
            name='frequency_interval',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='maintenanceprogram',
            name='maintenance_type',
            field=models.CharField(choices=[('preventive', 'Préventive'), ('inspection', 'Inspection'), ('calibration', 'Calibration'), ('control', 'Contrôle')], default='preventive', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenanceprogram',
            name='next_generation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceprogram',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='maintenanceprogram',
            name='notify_internal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='maintenanceprogram',
            name='notify_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenanceprogram',
            name='priority',
            field=models.CharField(choices=[('low', 'Faible'), ('normal', 'Normale'), ('high', 'Haute'), ('critical', 'Critique')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenanceprogram',
            name='required_parts',
            field=models.ManyToManyField(blank=True, related_name='maintenance_programs', to='sav.sparepart'),
        ),
        migrations.AddField(
            model_name='maintenanceprogram',
            name='scheduled_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='maintenanceprogram',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceprogram',
            name='team_members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ('cfao_manager', 'cfao_works', 'hvac_manager', 'chief_technician', 'technician')}, related_name='maintenance_program_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenanceprogram',
            name='technician',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ('cfao_manager', 'cfao_works', 'hvac_manager', 'chief_technician', 'technician')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_maintenance_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenanceprogram',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publie'), ('archived', 'Archive'), ('suspended', 'Suspendu')], default='draft', max_length=20),
        ),
    ]
