# Generated by Django 6.0.5 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sav", "0043_maintenance_program_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceticket",
            name="planned_duration_minutes",
            field=models.PositiveIntegerField(default=60),
        ),
    ]
