# Generated by Django 6.0.5 on 2026-07-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sav", "0044_maintenanceticket_planned_duration_minutes")]

    operations = [
        migrations.AddField(model_name="maintenanceprogram", name="city", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="maintenanceprogram", name="custom_frequency_unit", field=models.CharField(choices=[("days", "jours"), ("weeks", "semaines"), ("months", "mois"), ("years", "années")], default="days", max_length=12)),
        migrations.AddField(model_name="maintenanceprogram", name="description", field=models.TextField(blank=True)),
        migrations.AddField(model_name="maintenanceprogram", name="monthly_rule", field=models.CharField(blank=True, max_length=40)),
        migrations.AddField(model_name="maintenanceprogram", name="notification_days_before", field=models.PositiveSmallIntegerField(default=3)),
        migrations.AddField(model_name="maintenanceprogram", name="overnight_stays", field=models.PositiveSmallIntegerField(default=0)),
        migrations.AddField(model_name="maintenanceprogram", name="reference", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name="maintenanceprogram", name="site", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="maintenance_programs", to="sav.clientsite")),
        migrations.AddField(model_name="maintenanceprogram", name="weekly_days", field=models.JSONField(blank=True, default=list)),
        migrations.AlterField(model_name="maintenanceprogram", name="frequency", field=models.CharField(choices=[("daily", "Quotidienne"), ("weekly", "Hebdomadaire"), ("monthly", "Mensuelle"), ("quarterly", "Trimestrielle"), ("semiannual", "Semestrielle"), ("annual", "Annuelle"), ("custom", "Personnalisée")], default="monthly", max_length=20)),
        migrations.AlterField(model_name="maintenanceprogram", name="maintenance_type", field=models.CharField(choices=[("preventive", "Préventive"), ("inspection", "Inspection"), ("calibration", "Calibration"), ("control", "Contrôle"), ("periodic_check", "Vérification périodique")], default="preventive", max_length=20)),
        migrations.CreateModel(name="MaintenanceProgramPart", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("quantity", models.PositiveIntegerField(default=1)), ("observation", models.CharField(blank=True, max_length=255)), ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="planned_parts", to="sav.maintenanceprogram")), ("spare_part", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="maintenance_program_part_lines", to="sav.sparepart"))], options={"ordering": ["id"]}),
    ]
